name: gold_project
description: "This project is for shopkeer who can purchase jewellary from wholeseller."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  bloc:
  shared_preferences:
  shimmer:
  http:
  flutter_bloc:
  firebase_core: ^2.24.0
  firebase_messaging: ^14.7.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: InterRegular
      fonts:
        - asset: assets/fonts/Inter/static/Inter_24pt-Regular.ttf
    - family: InterSemiBold
      fonts:
        - asset: assets/fonts/Inter/static/Inter_18pt-SemiBold.ttf
    - family: InterMedium
      fonts:
        - asset: assets/fonts/Inter/static/Inter_18pt-Medium.ttf
    - family: RobotoRegular
      fonts:
        - asset: assets/fonts/Roboto/static/Roboto-Regular.ttf
    - family: RobotoMedium
      fonts:
        - asset: assets/fonts/Roboto/static/Roboto-Medium.ttf
    - family: BookantiquaBold
      fonts:
        - asset: assets/fonts/Book Antiqua/bookantiqua_bold.ttf

  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
